services:
  api_service:
    build: .
    restart: on-failure
    ports:
      - 8081:8080
    networks:
      - springapimysql-net
    environment:
      - spring.profiles.active=mysql
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/cda-bdd?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=admin
      - spring.jpa.hibernate.ddl-auto=create
      - spring.jpa.generate-ddl=true
      - spring.jpa.show-sql=true
      - spring.jpa.properties.hibernate.format_sql=true
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
      - server.port=8080
      - spring.datasource.hikari.initialization-fail-timeout=60000
      - spring.datasource.hikari.connection-timeout=60000
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: cda-bdd
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  springapimysql-net:
    driver: bridge
